### ISSUE TITLE
Missing `tslib` dependency

### ISSUE THREAD

**Issue by RomainCscnLF** [koblas/ibankit-js#11]
## Description

After trying to release a project using your lib, I encountered the following error:

```javascript
Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/space/www/my-project/data/releases/20200430123219/node_modules/ibankit/lib/exceptions.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/space/www/my-project/data/releases/20200430123219/node_modules/ibankit/lib/bbanStructure.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/space/www/my-project/data/releases/20200430123219/node_modules/ibankit/lib/index.js:5:23)
```

The important line from above is the following one where `tslib` is required:
```javascript
at Object.<anonymous> (/space/www/my-project/data/releases/20200430123219/node_modules/ibankit/lib/exceptions.js:3:15)
```

The error comes from the fact that the library is working fine when there is dev dependencies (containing `tslib`) but not on an environment where `tslib` is not in the dependencies.

## How to fix

Add [`tslib`](https://www.npmjs.com/package/tslib) in the dependency.

**Comment by koblas** [comment]
Small configuration change needed to tsconfig.json -- should be fixed now.

**Comment by RomainCscnLF** [comment]
Perfect, thanks a lot.
